# Generated by Django 4.0.6 on 2022-08-02 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madina', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.wilaya')),
            ],
        ),
    ]
