# Generated by Django 4.0.6 on 2022-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='wilaya',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
